/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.sena.examplejpa.view;

/**
 *
 * @author USUARIO
 */
public class JFrameHome extends javax.swing.JFrame {

    /**
     * Creates new form JFrameHome
     */
    public JFrameHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonEmployeeType = new javax.swing.JButton();
        jButtonEmployee = new javax.swing.JButton();
        jButtonKey = new javax.swing.JButton();
        jButtonRecord = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEmployeeType.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEmployeeType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEmployeeType.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEmployeeType.setText("Tipos de funcionarios");
        jButtonEmployeeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmployeeTypeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEmployeeType, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 86, -1, -1));

        jButtonEmployee.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEmployee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEmployee.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEmployee.setText("Funcionarios");
        jButtonEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 152, 150, -1));

        jButtonKey.setBackground(new java.awt.Color(255, 255, 255));
        jButtonKey.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonKey.setForeground(new java.awt.Color(0, 0, 0));
        jButtonKey.setText("LLaves");
        jButtonKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeyActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 219, 150, -1));

        jButtonRecord.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRecord.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonRecord.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRecord.setText("Registros");
        jButtonRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecordActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 288, 150, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("MASTER KEY 1.0");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 30, 147, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/sena/example/jpa/view/home_black.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/sena/example/jpa/view/imagen-javaa.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 260, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEmployeeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmployeeTypeActionPerformed
        JFrameEmployeeType view = new JFrameEmployeeType();
        view.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonEmployeeTypeActionPerformed

    private void jButtonEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmployeeActionPerformed
//       JFrameEmployee view = new JFrameEmployee();
//       view.setVisible(true);
//        setVisible(false);
    }//GEN-LAST:event_jButtonEmployeeActionPerformed

    private void jButtonKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeyActionPerformed
//        JFrameKey view = new JFrameKey();
//        view.setVisible(true);
 //       setVisible(false);
    }//GEN-LAST:event_jButtonKeyActionPerformed

    private void jButtonRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecordActionPerformed
       // JFrameRecord view = new JFrameRecord();
        //view.setVisible(true);
 //       setVisible(false);
    }//GEN-LAST:event_jButtonRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEmployee;
    private javax.swing.JButton jButtonEmployeeType;
    private javax.swing.JButton jButtonKey;
    private javax.swing.JButton jButtonRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
